language: node_js
cache: false
node_js:
  - '10'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
- stage: test
  script: yarn test
  skip_cleanup: true
- stage: release
    if: branch = master
    node_js: lts/*
    deploy:
      provider: script
      skip_cleanup: true
      script:
        - npx semantic-release
